# Generated by Django 3.1.14 on 2023-03-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
