# Generated by Django 3.1.14 on 2023-04-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
