# Generated by Django 3.1.14 on 2023-04-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230402_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('科技', 'tech'), ('生活', 'life')], max_length=50, null=True),
        ),
    ]
