# Generated by Django 3.1.14 on 2023-04-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20230404_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='myapp.article'),
        ),
    ]
